### PR TITLE
ENG-179 Remove `ring` dependency from aptos-crypto and pare down dependent code

### PR DESCRIPTION
**Pull request by mzabaluev**
### Description

`ring` is one of the obstacles for porting Aptos VM to RISC0.
In aptos-crypto, it's only used in Noise support code that is used by networking.
Cut out the noise module and ~~any~~ some crates depending on it.

`ring` is also used in the `aptos-types` crate, but only in the test utilities.
Gate these under the "testing" feature and make `ring` an optional dependency.

### Test Plan

Try to integrate the modified crates into the movement SDK and test if they build with the RISC0 toolchain.

### CODE REVIEW

**Comment by mzabaluev** [comment]
### Note to reviewers

Commits https://github.com/movementlabsxyz/aptos-core/pull/5/commits/cf6d5627874098d0e405a395933dfdd05d0d8eb2 and https://github.com/movementlabsxyz/aptos-core/pull/5/commits/392dfbb4b7542b2510f54748f5659c185cf0a64a have meaningful changes, the rest is bulk removal and committing the updated `Cargo.lock`.

**Comment by 0xmovses** [comment]
I'll test this by pulling in this commit into https://github.com/movementlabsxyz/movement/pull/30 and running CI.

**Comment by l-monninger** [comment]
@mzabaluev I've made you a container so you don't have to use the fork flow anymore.

**Comment by l-monninger** [comment]
Enjoying watching this get hacked down!

**Comment by mzabaluev** [comment]
I'm going to wield the machete of "we ain't gonna need it" :hocho: here and elsewhere.

It looks like some rebasing is in order, too. Will attend to it soon.

**Comment by mzabaluev** [comment]
Overhauled with fewer crates cut down, by moving noise support, and its `ring` dependency, to aptos-network.

The significant changes are in https://github.com/movementlabsxyz/aptos-core/pull/5/commits/a70ac2e4ea4f9a3a710821f7a6f6dda32f9b61e1

**Comment by 0xmovses** [comment]
Thanks for this! How how you tested this against the `monza` branch of this repo? https://github.com/movementlabsxyz/movement. Curious how you tested this exactly, did you update the `rev` value of in the Cargo.toml to use `aptos-core` from this branch?

**Comment by mzabaluev** [comment]
> Curious how you tested this exactly, did you update the `rev` value of in the Cargo.toml to use `aptos-core` from this branch?

Yes, the changes in https://github.com/movementlabsxyz/movement/pull/35 only based on `monza`. I can update that PR with the `monza` baseline, but I'm hesitant because yesterday you suggested to integrate against https://github.com/movementlabsxyz/movement/pull/34 and it did uncover issues.

**Comment by 0xmovses** [comment]
Let's go with `monza` as our point of truth. Then as PRs get merged in to it we can control the changes in `aptos-core`.

**Comment by 0xmovses** [comment]
There is this too https://github.com/movementlabsxyz/aptos-core/pull/6 but its my PR so I'll check it.

**Pull request merged**
