### PR TITLE
Remove crates: aptos, aptos-debugger

### PR DESCRIPTION
**Pull request by mzabaluev**
## Description

Unbreak the workspace by removing upstream crates which we don't need yet, but which have dependencies on other crates that have been removed in our fork and not added back in #34.

## Unresolved issues

The build (e.g. `cargo check --workspace`) is still broken and needs more crates to be synced.

### CODE REVIEW

**Review by andyjsbell — APPROVED** [review]
thanks @mzabaluev

**Comment by andyjsbell** [comment]
how can I confirm this exactly?

**Comment by mzabaluev** [comment]
> how can I confirm this exactly?

If you have any pending work in the movement repo using these crates (e.g. the CLI), we need to take a look if it's possible to feature-gate them; if not, then we should restore for real together with any of their dependencies.

**Comment by mzabaluev** [comment]
As far as I can see, the removed crates are not yet used in movement (in the `main` branch).

**Comment by mzabaluev** [comment]
Rebased just to sign the commit.

**Pull request merged**
